language: julia
os:
  - linux
  - osx
julia:
  - nightly
notifications:
  email: false
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); cd(Pkg.dir("ZChop")); using Coverage; Coveralls.submit(process_folder()); Codecov.submit(process_folder())'
